package com.travel_recommender.opta;

import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Day extends AbstractPersistable {

	private int start_time;
	private int end_time;
	private int lunch_start_time;
	private int lunch_end_time;
	private int dinner_start_time;
	private int dinner_end_time;
	private int week_day;
	private int CapsuleDuration;
	private List<TimeCapsule> timeCapsules;
	private int score;		// default is 1

	public Day() {
		super();
	}

	public int getStart_time() {
		return this.start_time;
	}

	public void setStart_time(int start_time) {
		this.start_time = start_time;
	}

	public int getEnd_time() {
		return this.end_time;
	}

	public void setEnd_time(int end_time) {
		this.end_time = end_time;
	}

	public int getLunch_start_time() {
		return this.lunch_start_time;
	}

	public void setLunch_start_time(int lunch_start_time) {
		this.lunch_start_time = lunch_start_time;
	}

	public int getLunch_end_time() {
		return this.lunch_end_time;
	}

	public void setLunch_end_time(int lunch_end_time) {
		this.lunch_end_time = lunch_end_time;
	}

	public int getDinner_start_time() {
		return this.dinner_start_time;
	}

	public void setDinner_start_time(int dinner_start_time) {
		this.dinner_start_time = dinner_start_time;
	}

	public int getCapsuleDuration() {
		return CapsuleDuration;
	}

	public void setCapsuleDuration(int capsuleDuration) {
		CapsuleDuration = capsuleDuration;
	}

	public int getDinner_end_time() {
		return this.dinner_end_time;
	}

	public void setDinner_end_time(int dinner_end_time) {
		this.dinner_end_time = dinner_end_time;
	}

	public int getWeek_day() {
		return this.week_day;
	}

	public void setWeek_day(int week_day) {
		this.week_day = week_day;
	}

	// Notice: `ID` here refers to Relative Index within EACH DAY
	public int getRelativeTimeCapsuleIndex(int timeInMinute) {
		return (int) Math.ceil((timeInMinute - this.start_time) / CapsuleDuration);
	}

	public boolean notMealTime(long timeCapsuleId) {
		int relativeId = (int) timeCapsuleId % getRelativeTimeCapsuleIndex(end_time);
		return relativeId < getRelativeTimeCapsuleIndex(lunch_start_time) || relativeId > getRelativeTimeCapsuleIndex(dinner_end_time) ||
				(relativeId > getRelativeTimeCapsuleIndex(lunch_end_time) && relativeId < getRelativeTimeCapsuleIndex(dinner_start_time));
	}


	public List<TimeCapsule> getTimeCapsules() {
		return this.timeCapsules;
	}

	public void setTimeCapsules(List<TimeCapsule> timeCapsules) {
		this.timeCapsules = timeCapsules;
	}

	public int getScore() {
		return score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public Day(Long id, int start_time, int end_time, int lunch_start_time,
			   int lunch_end_time, int dinner_start_time, int dinner_end_time,
			   int week_day, int score, int capsuleDuration) {
		super(id);
		this.start_time = start_time;
		this.end_time = end_time;
		this.lunch_start_time = lunch_start_time;
		this.lunch_end_time = lunch_end_time;
		this.dinner_start_time = dinner_start_time;
		this.dinner_end_time = dinner_end_time;
		this.week_day = week_day;
		this.score = score;
		this.CapsuleDuration = capsuleDuration;
	}

	@Override
	public String toString() {
		return "Day{" +
				"start_time=" + start_time +
				", end_time=" + end_time +
				", lunch_start_time=" + lunch_start_time +
				", lunch_end_time=" + lunch_end_time +
				", dinner_start_time=" + dinner_start_time +
				", dinner_end_time=" + dinner_end_time +
				", week_day=" + week_day +
				", CapsuleDuration=" + CapsuleDuration +
				", timeCapsules=" + timeCapsules +
				", score=" + score +
				'}';
	}
}
